on:
  push:
    branches: 
      - ci_build

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    name: Publish Logseq graph
    steps:
      - uses: actions/checkout@v3
      - uses: logseq/publish-spa@v0.3.0
        with:
          theme-mode: dark
          accent-color: green
          output-directory: build
      - name: Add a nojekyll file # to make sure asset paths are correctly identified
        run: touch $GITHUB_WORKSPACE/build/.nojekyll
      - name: Deploy to Netlify
        uses: jsmrcaga/action-netlify-deploy@v2.2.0
        with:
          build_directory: build
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Deployed on new master commit"
          NETLIFY_DEPLOY_TO_PROD: true
          install_command: "echo Skipping installing deps"
          build_command: "echo Skipping building"
